# Generated by Django 3.2.12 on 2022-06-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='ShopPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shops/')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.shop')),
            ],
        ),
    ]
